import { createElement } from 'lwc';
import Lwc_parent_card_and_detail_page from 'c/lwc_parent_card_and_detail_page';

describe('c-lwc-parent-card-and-detail-page', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-parent-card-and-detail-page', {
            is: Lwc_parent_card_and_detail_page
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});