import { createElement } from 'lwc';
import Pass_value_from_lwc_Apexclass from 'c/pass_value_from_lwc_Apexclass';

describe('c-pass-value-from-lwc-apexclass', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-pass-value-from-lwc-apexclass', {
            is: Pass_value_from_lwc_Apexclass
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});