import { createElement } from 'lwc';
import Lwc_pass_data_to_components from 'c/lwc_pass_data_to_components';

describe('c-lwc-pass-data-to-components', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-pass-data-to-components', {
            is: Lwc_pass_data_to_components
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});