import { createElement } from 'lwc';
import Lwc_addCard_andDetail_page from 'c/lwc_addCard_andDetail_page';

describe('c-lwc-add-card-and-detail-page', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-add-card-and-detail-page', {
            is: Lwc_addCard_andDetail_page
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});